"""Emit src/components/brand/Logo.tsx with the path data inlined.

Inlining (rather than <img src="/brand/...">) is what makes `currentColor`
work, so the mark inherits the theme instead of needing a light/dark pair.
"""
import re, os

OUT = 'public/brand'

def paths_of(f):
    s = open(os.path.join(OUT, f)).read()
    vb = re.search(r'viewBox="([^"]*)"', s).group(1)
    return vb, re.findall(r'<path[^>]*\sd="([^"]*)"', s)

mvb, mds = paths_of('mark.svg')
evb, eds = paths_of('lockup-en.svg')

def jsx(ds, indent):
    return ('\n' + indent).join('<path d="%s" />' % d for d in ds)

tsx = '''/*
 * METRIX brand marks.
 *
 * GENERATED by scripts/brand/build_component.py — do not hand-edit the path
 * data. Run ./scripts/brand/build.sh to regenerate.
 *
 * Everything paints in `currentColor`, so one component covers both themes.
 * That is what replaced the old logo1.svg / logo2.svg pair swapped with
 * `dark:hidden`.
 *
 * The wordmark is Latin only — METRIX. There is deliberately no Arabic
 * lockup; see BRAND.md.
 */
import type { SVGProps } from "react";

/* The bare star. Use where the name is already on screen. */
export function BrandMark({
  title,
  ...props
}: SVGProps<SVGSVGElement> & { title?: string }) {
  return (
    <svg
      viewBox="%(mvb)s"
      fill="currentColor"
      role={title ? "img" : "presentation"}
      aria-hidden={title ? undefined : true}
      aria-label={title}
      {...props}
    >
      %(mp)s
    </svg>
  );
}

/* Star + METRIX, horizontal. The only lockup. */
export function BrandLockup(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      viewBox="%(evb)s"
      fill="currentColor"
      role="img"
      aria-label="METRIX"
      {...props}
    >
      %(ep)s
    </svg>
  );
}
''' % dict(mvb=mvb, mp=jsx(mds, '      '), evb=evb, ep=jsx(eds, '      '))

os.makedirs('src/components/brand', exist_ok=True)
open('src/components/brand/Logo.tsx', 'w').write(tsx)
print("Logo.tsx written: %d bytes (mark %d paths, lockup %d)" % (len(tsx), len(mds), len(eds)))
