import type { Metadata, Viewport } from "next";
import { IBM_Plex_Sans_Arabic, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";

/*
 * Both families are loaded here, not through a `@import url(...)` in
 * globals.css. That import was silently dropped from the compiled stylesheet by
 * Tailwind v4, so neither font had ever reached the browser and the whole app
 * was rendering in the OS default sans-serif. next/font self-hosts the files,
 * preloads them, and emits a size-adjusted local fallback so the swap does not
 * reflow.
 *
 * These two calls exist to REGISTER the @font-face rules and preload the
 * files. globals.css does not consume `--font-latin` / `--font-ibm-arabic` in
 * its font stacks, and that is deliberate — see below. The `.variable` classes
 * stay on <html> because dropping them would drop the stylesheet that carries
 * the @font-face rules along with them.
 *
 * Why the variables are unusable in a stack:
 *
 * next/font appends a companion face per family — `"Plus Jakarta Sans
 * Fallback"`, `src: local("Arial")`, `size-adjust: 104.98%` — and folds it
 * INTO the variable, so `--font-latin` expands to TWO families, not one. That
 * companion carries no `unicode-range`, so it defaults to U+0-10FFFF and
 * matches every codepoint in existence. Composed as
 * `var(--font-latin), var(--font-ibm-arabic)` it lands between the two real
 * families and terminates per-glyph matching on the first Arabic character:
 * every Arabic glyph rendered in Arial, which macOS does ship with Arabic
 * coverage, and all sixteen IBM Plex Sans Arabic faces sat at
 * `status: "unloaded"` while the page looked finished.
 *
 * `adjustFontFallback: false` is the documented off switch and does NOT work
 * here: on Next 16.3.2 the option is absent from next/font's types and the
 * validator strips it before the loader sees it, so the emitted CSS still
 * reads `--font-latin:"Plus Jakarta Sans", "Plus Jakarta Sans Fallback"`.
 * globals.css therefore names both families literally instead.
 *
 * Arabic tops out at weight 700 (Google ships no 800/900 for this family), so
 * `font-extrabold`/`font-black` on Arabic render at 700 — nearest declared
 * weight, not a synthesised faux-bold.
 */
const fontArabic = IBM_Plex_Sans_Arabic({
  subsets: ["arabic", "latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-ibm-arabic",
  display: "swap",
});

const fontLatin = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-latin",
  display: "swap",
});

/*
 * Brand assets live in `public/brand/` and are generated, not hand-drawn — see
 * BRAND.md. The wordmark is Latin only: METRIX, always all-caps. The UI copy is
 * still Arabic-first; only the identity is English.
 */
export const metadata: Metadata = {
  metadataBase: new URL("https://metrix-ruddy.vercel.app"),
  title: {
    default: "METRIX",
    template: "%s — METRIX",
  },
  description: "Turn any goal into a plan you can actually follow.",
  applicationName: "METRIX",
  icons: {
    // No .ico here: `src/app/favicon.ico` is picked up by Next's file
    // convention and already emits one, so listing it again duplicates the tag.
    // That file is a copy of public/brand/favicon.ico — regenerate both together.
    icon: [
      { url: "/brand/favicon.svg", type: "image/svg+xml" },
      { url: "/brand/icon-192.png", type: "image/png", sizes: "192x192" },
      { url: "/brand/icon-512.png", type: "image/png", sizes: "512x512" },
    ],
    apple: [{ url: "/brand/apple-touch-icon.png", sizes: "180x180" }],
  },
  // manifest is generated by src/app/manifest.ts; Next links it automatically
  openGraph: {
    type: "website",
    siteName: "METRIX",
    title: "METRIX",
    description: "Turn any goal into a plan you can actually follow.",
    locale: "ar_IQ",
    alternateLocale: ["en_US"],
    images: [{ url: "/brand/og.png", width: 1200, height: 630, alt: "METRIX" }],
  },
  twitter: {
    card: "summary_large_image",
    title: "METRIX",
    description: "Turn any goal into a plan you can actually follow.",
    images: ["/brand/og.png"],
  },
};

/*
 * Both values are `--canvas`, the ground `body` actually paints (bg-canvas),
 * not `--background`. Using #fff/#000 here makes the browser chrome disagree
 * with the page on both themes.
 */
export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#f7f7f7" },
    { media: "(prefers-color-scheme: dark)", color: "#000000" },
  ],
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ar"
      dir="rtl"
      className={`${fontArabic.variable} ${fontLatin.variable}`}
      suppressHydrationWarning
    >
      <body
        className="font-sans antialiased bg-canvas text-foreground selection:bg-primary/20"
      >
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  const savedTheme = localStorage.getItem('theme');
                  const systemTheme = window.matchMedia('(prefers-color-scheme: dark)').matches;
                  
                  if (savedTheme === 'dark') {
                    document.documentElement.classList.add('dark');
                  } else {
                    document.documentElement.classList.remove('dark');
                  }
                } catch (e) {}
              })();
            `,
          }}
        />
        {children}
      </body>
    </html>
  );
}
