import type { MetadataRoute } from "next";

/*
 * Generated by Next rather than served as a static file from `public/`, so the
 * response always carries `application/manifest+json`. A plain
 * `public/site.webmanifest` depends on the host's MIME table — the dev server
 * hands it back as `text/html`.
 *
 * Colours are `--canvas` dark (#060606), the ground `body` actually paints.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "METRIX",
    short_name: "METRIX",
    description: "Turn any goal into a plan you can actually follow.",
    // These label the manifest's own strings, which are now English. The app
    // UI is still Arabic-first — that is set on <html> in layout.tsx.
    lang: "en",
    dir: "ltr",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#060606",
    theme_color: "#060606",
    icons: [
      { src: "/brand/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/brand/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/brand/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
